### ISSUE TITLE
[im_dad, just_met_her , no_fuck_you] cogs are not getting triggered

### ISSUE THREAD

**Issue by holysheep** [TheDataLeek/Eris-Cogs#63]
Aforementioned cogs are not working, for example:

<img width="259" alt="Screenshot 2024-03-22 at 16 09 40" src="https://github.com/TheDataLeek/Eris-Cogs/assets/9785806/2f1727f1-c0b2-4910-9e74-0826a29ef9a8">  

Regex seems to be correct:

```
import re

class RegexChecker:
    def __init__(self):
        self.pattern = re.compile(r"\bf[uck]{,3} \b", flags=re.IGNORECASE)

    def check_string(self, input_string):
        if self.pattern.search(input_string):
            return True
        else:
            return False


checker = RegexChecker()
print(checker.check_string("Well, fuck you!")) # output is True
```

Bot have majority of permissions. Do I miss something?

**Comment by TheDataLeek** [comment]
Yes - you also need to install the `event_config` cog in order to allow the events to fire. My apologies for the convoluted install - here’s some motivation behind it

* I have a few of these cogs that have unprompted bot actions based on trigger words or phrases
* There’s not a supported way to have cogs share library code (or at least there wasn’t, I haven’t checked recently)
* The best way to configure many of these events at once is to then require an additional cog, the `event_config` cog to be installed as well in order to change the allowlist/denylists for events based on guilds+channels

Once you’ve installed that, use `.econf` to establish permitted channels for the events to fire in!

**Comment by holysheep** [comment]
Thank you, all set!
